version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: news_ai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: golang:1.21
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    command: >
      sh -c "go install github.com/pressly/goose/v3/cmd/goose@latest &&
             goose postgres 'postgres://postgres:postgres@postgres:5432/news_ai?sslmode=disable' up"

volumes:
  postgres_data: 